name: Release to Discord

on:
  release:
    types: [ published ]

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Github Releases To Discord
        shell: bash
        run: |
          payload="$(jq -n \
            --arg content "||@everyone||" \
            --arg username "Laravel QrCode" \
            --arg avatarUrl "https://avatars.githubusercontent.com/u/116525492?s=96&v=4" \
            --arg title "${{ github.event.release.name || github.event.release.tag_name }}" \
            --arg url "${{ github.event.release.html_url }}" \
            --arg footerTitle "Laravel QrCode" \
            --arg footerIconUrl "https://avatars.githubusercontent.com/u/116525492?s=96&v=4" \
            --arg timestamp "${{ github.event.release.published_at }}" \
            '{content: $content, username: $username, avatar_url: $avatarUrl, embeds: [{title: $title, url: $url, color: 2105893, footer: {text: $footerTitle, icon_url: $footerIconUrl}, timestamp: $timestamp}]}')"

          curl --fail --silent --show-error \
            --header "Content-Type: application/json" \
            --data "$payload" \
            "${{ secrets.DISCORD }}"
